'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ATTimeCardDetails1
    
    '''<summary>
    '''ScriptBlockGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptBlockGeneral As Global.Telerik.Web.UI.RadScriptBlock
    
    '''<summary>
    '''AjaxManagerGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AjaxManagerGeneral As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''PnlGridContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlGridContent As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PnlGeneralBtnTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlGeneralBtnTop As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ImgPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgPhoto As Global.Telerik.Web.UI.RadBinaryImage
    
    '''<summary>
    '''liName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ddlEmpList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmpList1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''laFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents laFilter As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''liFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liFrom As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''liFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liFromDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbxOvernight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxOvernight As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''liTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liTo As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''liaToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liaToDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbxApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbxApproved As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lnkbtnAdHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAdHours As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnAddHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAddHours As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtnAddPunch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAddPunch As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LnkBtnPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkBtnPrevious As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LnkBtnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkBtnNext As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''liMissPunch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liMissPunch As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''liMismatchedPunchTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liMismatchedPunchTypes As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''NTSGeneralGridTC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTSGeneralGridTC As Global.Osi.AlChavo.Common.Controls.NetsoftGrid
    
    '''<summary>
    '''NTSGridHoursSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTSGridHoursSum As Global.Osi.AlChavo.Common.Controls.NetsoftGrid
    
    '''<summary>
    '''ContentTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LiHoursRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiHoursRegister As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''liApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liApproved As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''GeneralHoursGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralHoursGrid As Global.Osi.AlChavo.Common.Controls.NetsoftGrid
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''liAdditionalHOurs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAdditionalHOurs As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''AdditionalGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdditionalGrid As Global.Osi.AlChavo.Common.Controls.NetsoftGrid
    
    '''<summary>
    '''NTSGridSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NTSGridSchedule As Global.Osi.AlChavo.Common.Controls.NetsoftGrid
    
    '''<summary>
    '''lnkBtnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtnEdit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkBtn_Previous control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBtn_Previous As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkbtn_NextPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtn_NextPeriod As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''HfFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HfFilter As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HdfclosePopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HdfclosePopUp As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ATC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ATC As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''Warn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Warn As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''LoadingPanelGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingPanelGeneral As Global.Telerik.Web.UI.RadAjaxLoadingPanel
    
    '''<summary>
    '''RdwPunchDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdwPunchDetail As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''RdwAddHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdwAddHours As Global.Telerik.Web.UI.RadWindow
    
    '''<summary>
    '''RdwWrn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdwWrn As Global.Telerik.Web.UI.RadWindow
End Class
